#!/bin/sh

set -eu

cargo fmt
if ! cargo fmt -- --check
then
    echo "There are some code style issues."
    echo "Run cargo fmt first."
    exit 1
fi

cargo clippy --fix --allow-staged
# This shit is too strict for me:
# if ! cargo clippy --all-targets -- -D warnings
# then
#     echo "There are some clippy issues."
#     exit 1
# fi

# if ! cargo test
# then
#     echo "There are some test issues."
#     exit 1
# fi

# Add clippied shit to the commit
git add .

exit 0